site_name: Copyright Footer
site_url: https://project.pages.drupalcode.org/copyright_footer/4.x/
repo_url: https://git.drupalcode.org/project/copyright_footer
repo_name: drupal/copyright_footer
edit_uri: -/tree/4.x/docs/

theme:
  name: material
  features:
    - navigation.footer
    - content.action.edit
    - content.action.view

plugins:
  - search

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Block configuration: configuration.md
